config/routes.rb
Homerkr::Application.routes.draw do

  root :to => 'home#index'
  resources :students, :only => [:index, :new, :create]

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  attr_accessible :name, :size
  has_and_belongs_to_many :students
end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :name
  has_and_belongs_to_many :assignments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
    @student = Student.new
  end
  def create
    student = Student.create(params[:student])
    student.save
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
= link_to("Students", students_path)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Homerkr</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/_form.html.haml
= form_for @student, :url => students_path, :remote => true do |f|
  = f.label :name
  = f.text_field :name
  = button_to_function('Cancel', 'cancel_student_form()')
  = f.submit

app/views/students/create.js.erb
<% if @student.valid? %>
  $('#student_form').empty().after('<p>you created a student</p>');
<% else %>
  $('#student_form').empty().append('<%=j render(:partial => 'form') %>');
<% end %>

app/views/students/index.html.haml
= link_to('Add New Student', new_student_path, :remote => true)
#student_form

app/views/students/new.js.erb
$('#student_form').empty().append('<%=j render(:partial => 'form') %>');